# Generated by Django 4.2.4 on 2023-08-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='food_pics'),
        ),
    ]
